### PR TITLE
Added requirements.txt

### PR DESCRIPTION
**Pull request by shathor**
Added requirements.txt created with "pipreqs" to make it easier to initially build the application.

### CODE REVIEW

**Comment by JonathanTaquet** [comment]
Thank you for your contribution.
py2exe is not required to run the application, but I don't know how 'requirements.txt' file is usually used. Is it only for building the executable application? We may think to rename it in something like: 'requirements-build-win-py2exe.txt' (or something else if better) as pyinstaller can also be used and as py2exe is only for windows builds.

**Comment by shathor** [comment]
_requirements.txt_ is similar to setup.py, but has some advantages: http://stackoverflow.com/a/15731459 
You can build the application with pip (_pip install -r /path/to/requirements.txt_). The file shouldn't be renamed to something else.

It's mainly useful for developers to easily aquire all required libraries directly without having to look for them manually. I don't think it is an issue of py2exe will also be downloaded (especially with virtualenv) eventhough it is not required to run Oe2sSLE. However it is apparently required to compile. If its not there, somewhere your code is invalid.

Edit: Just saw it is used in setup.py. Maybe move that file out of the root module or even better the Windows installation part with py2exe. That way you can later also use setup.py to also install on Linux / Mac somehow.

**Comment by JonathanTaquet** [comment]
Ok,
thank you for your help, your explanations and advises.
I will keep it in mind and have a look at how to better organize the file tree and at how to manage the setup.py.
I think it will not be in my highest priorities (at least for now), but I keep it open as I think it is a good thing to do to have a cleaner project.

**Comment by JonathanTaquet** [comment]
I have removed setup.py as I do not use py2exe anymore.
I just added requirements.txt as you suggested (it now only require pyaudio)

**Pull request closed without merging**
